[package]
name = "dkic-signer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4"
ed25519-dalek = { version = "2", features = ["pkcs8", "pem", "rand_core"] }
rand = "0.8"
base64 = "0.22"
pkcs8 = "0.10"

[dev-dependencies]
tempfile = "3.0"
